services:
  # El motor de Base de Datos para almacenar las gestiones limpias
  db:
    image: postgres:15-alpine
    container_name: central_etl_postgres
    restart: always
    environment:
      POSTGRES_DB: central_etl_db
      POSTGRES_USER: etl_admin
      POSTGRES_PASSWORD: etl_password_segura_2026
    ports:
      - "5433:5432" # Puerto 5433 expuesto para que no choque con tu otra BD
    volumes:
      - postgres_multimandante_data:/var/lib/postgresql/data

  # El entorno de Python donde correrá tu Robot Enterprise y la API
  app:
    build: ./backend # <-- ACTUALIZADO: Ahora busca el Dockerfile en la carpeta backend
    container_name: central_etl_app
    restart: always
    ports:
      - "9090:5000" # <-- Puerto 9090 asignado para tu backend API (Flask)
    volumes:
      - ./backend:/app # <-- ACTUALIZADO: Ahora monta solo la carpeta backend
    environment:
      - DB_HOST=db
      - DB_NAME=central_etl_db
      - DB_USER=etl_admin
      - DB_PASSWORD=etl_password_segura_2026
      - DB_PORT=5432
    depends_on:
      - db

  # NUEVO: Tu entorno Frontend en Vue.js (Mudado al puerto 8088)
  frontend:
    build: ./frontend
    container_name: central_etl_vue
    restart: always
    ports:
      - "8088:8088" # <-- ¡Actualizado al nuevo puerto para evitar colisiones!
    volumes:
      - ./frontend:/app
      - /app/node_modules # Protege la instalación interna de librerías de Node
    depends_on:
      - app

volumes:
  postgres_multimandante_data: